### ISSUE TITLE
Preview is constantly crashing when migrated to AndroidX.

### ISSUE THREAD

**Issue by yevhenii-kanivets** [box/box-android-preview-sdk#22]
After migrating our project to AndroidX, Preview SDK is constantly crashing when trying to open any document preview.

I suppose it happens because of Box Preview SDK searches for `android/support/v4/app/FragmentActivity.getActivity()` method, which no more exists. AndroidX AS plugin usually just changes all such calls in library binaries, but I suppose here it doesn't work because of native library usage.

Our team will be very grateful if you could fix this issue in next release.

```
01-11 15:11:00.235 23742-23742/? W/dalvikvm: JNI WARNING: JNI function GetMethodID called with exception pending
01-11 15:11:00.235 23742-23742/? W/dalvikvm:              in Lcom/box/androidsdk/preview/fragments/BoxPreviewDocumentFragment;.getPdfFragment:(Lcom/box/androidsdk/preview/fragments/BoxPreviewDocumentFragment;)Lcom/box/androidsdk/preview/fragments/BoxPSPDFFragment; (GetMethodID)
01-11 15:11:00.235 23742-23742/? W/dalvikvm: Pending exception is:
01-11 15:11:00.235 23742-23742/? I/dalvikvm: java.lang.NoSuchMethodError: no method with name='getActivity' signature='()Landroid/support/v4/app/FragmentActivity;' in class Lcom/box/androidsdk/preview/fragments/BoxPreviewDocumentFragment;
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewDocumentFragment.getPdfFragment(Native Method)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewDocumentFragment.a(BoxPreviewDocumentFragment.java:274)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewDocumentFragment.onBoxRequestSuccess(BoxPreviewDocumentFragment.java:116)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewFragment.onTaskCompleted(BoxPreviewFragment.java:254)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewDocumentFragment.onTaskCompleted(BoxPreviewDocumentFragment.java:137)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.BoxPreviewViewPager.handleResponseQueue(BoxPreviewViewPager.java:302)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.BoxPreviewViewPager$1.onReceive(BoxPreviewViewPager.java:95)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at android.os.Looper.loop(Looper.java:136)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5017)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
01-11 15:11:00.235 23742-23742/? I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
01-11 15:11:00.235 23742-23742/? I/dalvikvm: "main" prio=5 tid=1 NATIVE
01-11 15:11:00.235 23742-23742/? I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0xa4c9cbd8 self=0xb7b854a0
01-11 15:11:00.235 23742-23742/? I/dalvikvm:   | sysTid=23742 nice=-6 sched=0/0 cgrp=[fopen-error:2] handle=-1217355680
01-11 15:11:00.235 23742-23742/? I/dalvikvm:   | state=R schedstat=( 0 0 0 ) utm=834 stm=525 core=2
01-11 15:11:00.255 23742-23742/? I/dalvikvm:   #00  pc 000bd4b6  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+86)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:   #01  pc 00098093  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+1155)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:   #02  pc 00098386  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+86)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:   #03  pc 0004ce17  /system/lib/libdvm.so (ScopedCheck::checkThread(int)+455)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:   #04  pc 0005eba5  /system/lib/libdvm.so
01-11 15:11:00.255 23742-23742/? I/dalvikvm:   #05  pc 000006c0  /data/app-lib/com.m360.android.debug-1/libbox-jni.so (_JNIEnv::GetMethodID(_jclass*, char const*, char const*)+46)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:   #06  pc 00000e51  /data/app-lib/com.m360.android.debug-1/libbox-jni.so (Java_com_box_androidsdk_preview_fragments_BoxPreviewDocumentFragment_getPdfFragment+423)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:   #07  pc 0002a0eb  /system/lib/libdvm.so (dvmPlatformInvoke+79)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewDocumentFragment.getPdfFragment(Native Method)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewDocumentFragment.a(BoxPreviewDocumentFragment.java:274)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewDocumentFragment.onBoxRequestSuccess(BoxPreviewDocumentFragment.java:116)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewFragment.onTaskCompleted(BoxPreviewFragment.java:254)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.fragments.BoxPreviewDocumentFragment.onTaskCompleted(BoxPreviewDocumentFragment.java:137)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.BoxPreviewViewPager.handleResponseQueue(BoxPreviewViewPager.java:302)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.box.androidsdk.preview.BoxPreviewViewPager$1.onReceive(BoxPreviewViewPager.java:95)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at android.os.Looper.loop(Looper.java:136)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5017)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
01-11 15:11:00.255 23742-23742/? I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
01-11 15:11:00.255 23742-23742/? E/dalvikvm: VM aborting
01-11 15:11:00.255 23742-23742/? A/libc: Fatal signal 6 (SIGABRT) at 0x00005cbe (code=-6), thread 23742 (0.android.debug)
01-11 15:11:00.315 1170-1170/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-11 15:11:00.315 1170-1170/? I/DEBUG: Build fingerprint: 'generic_x86/google_sdk_x86/generic_x86:4.4.2/KK/5056517:eng/test-keys'
01-11 15:11:00.315 1170-1170/? I/DEBUG: Revision: '0'
01-11 15:11:00.315 1170-1170/? I/DEBUG: pid: 23742, tid: 23742, name: 0.android.debug  >>> com.m360.android.debug <<<
01-11 15:11:00.315 1170-1170/? I/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-11 15:11:00.785 1170-1170/? I/DEBUG:     eax 00000000  ebx 00005cbe  ecx 00005cbe  edx 00000006
01-11 15:11:00.785 1170-1170/? I/DEBUG:     esi 00005cbe  edi 00000002
01-11 15:11:00.785 1170-1170/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
01-11 15:11:00.785 1170-1170/? I/DEBUG:     eip b7656c96  ebp b76bbce0  esp bfaf63d0  flags 00200207
01-11 15:11:00.795 1170-1170/? I/DEBUG: backtrace:
01-11 15:11:00.795 1170-1170/? I/DEBUG:     #00  pc 0003bc96  /system/lib/libc.so (tgkill+22)
01-11 15:11:00.795 1170-1170/? I/DEBUG:     #01  pc 00000005  <unknown>
01-11 15:11:00.795 1170-1170/? I/DEBUG: stack:
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf6390  00000000  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf6394  b76b7268  /system/lib/libc.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf6398  b76b72ab  /system/lib/libc.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf639c  b7628ef9  /system/lib/libc.so (pthread_mutex_unlock+25)
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63a0  b76b718c  /system/lib/libc.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63a4  b7bfe910  [heap]
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63a8  00000015  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63ac  b7628ef9  /system/lib/libc.so (pthread_mutex_unlock+25)
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63b0  00000000  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63b4  b7675656  /system/lib/libc.so (funlockfile+6)
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63b8  b76b6fcc  /system/lib/libc.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63bc  b7660c76  /system/lib/libc.so (__sflush_locked+150)
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63c0  00000000  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63c4  00000000  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63c8  b7628d29  /system/lib/libc.so (pthread_mutex_lock+9)
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63cc  b76b6fcc  /system/lib/libc.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:     #00  bfaf63d0  00000006  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63d4  00005cbe  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63d8  b76b6fcc  /system/lib/libc.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63dc  b7633436  /system/lib/libc.so (pthread_kill+102)
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63e0  00005cbe  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63e4  00005cbe  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63e8  00000006  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63ec  00000000  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63f0  b76b7268  /system/lib/libc.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63f4  b4e02fe1  /system/lib/libdvm.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63f8  b76333d9  /system/lib/libc.so (pthread_kill+9)
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf63fc  b76b6fcc  /system/lib/libc.so
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf6400  bfaf644c  [stack]
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf6404  bfaf668c  [stack]
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf6408  00000000  
01-11 15:11:00.795 1170-1170/? I/DEBUG:          bfaf640c  b76337fc  /system/lib/libc.so (raise+44)
```

**Comment by yev-kanivets** [comment]
Fixed with latest version.
